var annotated_dup =
[
    [ "disasm", null, [
      [ "Disassembler", "classdisasm_1_1_disassembler.html", "classdisasm_1_1_disassembler" ],
      [ "NameConverter", "classdisasm_1_1_name_converter.html", "classdisasm_1_1_name_converter" ]
    ] ],
    [ "std", null, [
      [ "hash< v8_inspector::String16 >", "structstd_1_1hash_3_01v8__inspector_1_1_string16_01_4.html", "structstd_1_1hash_3_01v8__inspector_1_1_string16_01_4" ]
    ] ],
    [ "unibrow", null, [
      [ "CanonicalizationRange", "structunibrow_1_1_canonicalization_range.html", "structunibrow_1_1_canonicalization_range" ],
      [ "Ecma262Canonicalize", "structunibrow_1_1_ecma262_canonicalize.html", "structunibrow_1_1_ecma262_canonicalize" ],
      [ "Ecma262UnCanonicalize", "structunibrow_1_1_ecma262_un_canonicalize.html", "structunibrow_1_1_ecma262_un_canonicalize" ],
      [ "ID_Continue", "structunibrow_1_1_i_d___continue.html", "structunibrow_1_1_i_d___continue" ],
      [ "ID_Start", "structunibrow_1_1_i_d___start.html", "structunibrow_1_1_i_d___start" ],
      [ "Latin1", "classunibrow_1_1_latin1.html", "classunibrow_1_1_latin1" ],
      [ "Letter", "structunibrow_1_1_letter.html", "structunibrow_1_1_letter" ],
      [ "LineTerminator", "structunibrow_1_1_line_terminator.html", "structunibrow_1_1_line_terminator" ],
      [ "Lowercase", "structunibrow_1_1_lowercase.html", "structunibrow_1_1_lowercase" ],
      [ "Mapping", "classunibrow_1_1_mapping.html", "classunibrow_1_1_mapping" ],
      [ "MultiCharacterSpecialCase", "structunibrow_1_1_multi_character_special_case.html", "structunibrow_1_1_multi_character_special_case" ],
      [ "Predicate", "classunibrow_1_1_predicate.html", "classunibrow_1_1_predicate" ],
      [ "ToLowercase", "structunibrow_1_1_to_lowercase.html", "structunibrow_1_1_to_lowercase" ],
      [ "ToUppercase", "structunibrow_1_1_to_uppercase.html", "structunibrow_1_1_to_uppercase" ],
      [ "UnicodeData", "classunibrow_1_1_unicode_data.html", "classunibrow_1_1_unicode_data" ],
      [ "Uppercase", "structunibrow_1_1_uppercase.html", "structunibrow_1_1_uppercase" ],
      [ "Utf16", "classunibrow_1_1_utf16.html", "classunibrow_1_1_utf16" ],
      [ "Utf8", "classunibrow_1_1_utf8.html", "classunibrow_1_1_utf8" ],
      [ "Utf8Decoder", "classunibrow_1_1_utf8_decoder.html", "classunibrow_1_1_utf8_decoder" ],
      [ "Utf8DecoderBase", "classunibrow_1_1_utf8_decoder_base.html", "classunibrow_1_1_utf8_decoder_base" ],
      [ "WhiteSpace", "structunibrow_1_1_white_space.html", "structunibrow_1_1_white_space" ]
    ] ],
    [ "v8", "namespacev8.html", "namespacev8" ],
    [ "v8_inspector", null, [
      [ "protocol", null, [
        [ "StringUtil", "classv8__inspector_1_1protocol_1_1_string_util.html", "classv8__inspector_1_1protocol_1_1_string_util" ]
      ] ],
      [ "InjectedScript", "classv8__inspector_1_1_injected_script.html", "classv8__inspector_1_1_injected_script" ],
      [ "InjectedScriptNative", "classv8__inspector_1_1_injected_script_native.html", "classv8__inspector_1_1_injected_script_native" ],
      [ "InspectedContext", "classv8__inspector_1_1_inspected_context.html", "classv8__inspector_1_1_inspected_context" ],
      [ "JavaScriptCallFrame", "classv8__inspector_1_1_java_script_call_frame.html", "classv8__inspector_1_1_java_script_call_frame" ],
      [ "RemoteCallFrameId", "classv8__inspector_1_1_remote_call_frame_id.html", "classv8__inspector_1_1_remote_call_frame_id" ],
      [ "RemoteObjectId", "classv8__inspector_1_1_remote_object_id.html", "classv8__inspector_1_1_remote_object_id" ],
      [ "RemoteObjectIdBase", "classv8__inspector_1_1_remote_object_id_base.html", "classv8__inspector_1_1_remote_object_id_base" ],
      [ "ScriptBreakpoint", "structv8__inspector_1_1_script_breakpoint.html", "structv8__inspector_1_1_script_breakpoint" ],
      [ "String16", "classv8__inspector_1_1_string16.html", "classv8__inspector_1_1_string16" ],
      [ "String16Builder", "classv8__inspector_1_1_string16_builder.html", "classv8__inspector_1_1_string16_builder" ],
      [ "StringBuffer", "classv8__inspector_1_1_string_buffer.html", "classv8__inspector_1_1_string_buffer" ],
      [ "StringBufferImpl", "classv8__inspector_1_1_string_buffer_impl.html", "classv8__inspector_1_1_string_buffer_impl" ],
      [ "StringView", "classv8__inspector_1_1_string_view.html", "classv8__inspector_1_1_string_view" ],
      [ "V8Console", "classv8__inspector_1_1_v8_console.html", "classv8__inspector_1_1_v8_console" ],
      [ "V8ConsoleAgentImpl", "classv8__inspector_1_1_v8_console_agent_impl.html", "classv8__inspector_1_1_v8_console_agent_impl" ],
      [ "V8ConsoleMessage", "classv8__inspector_1_1_v8_console_message.html", "classv8__inspector_1_1_v8_console_message" ],
      [ "V8ConsoleMessageStorage", "classv8__inspector_1_1_v8_console_message_storage.html", "classv8__inspector_1_1_v8_console_message_storage" ],
      [ "V8ContextInfo", "classv8__inspector_1_1_v8_context_info.html", "classv8__inspector_1_1_v8_context_info" ],
      [ "V8Debugger", "classv8__inspector_1_1_v8_debugger.html", "classv8__inspector_1_1_v8_debugger" ],
      [ "V8DebuggerAgentImpl", "classv8__inspector_1_1_v8_debugger_agent_impl.html", "classv8__inspector_1_1_v8_debugger_agent_impl" ],
      [ "V8DebuggerScript", "classv8__inspector_1_1_v8_debugger_script.html", "classv8__inspector_1_1_v8_debugger_script" ],
      [ "V8FunctionCall", "classv8__inspector_1_1_v8_function_call.html", "classv8__inspector_1_1_v8_function_call" ],
      [ "V8HeapProfilerAgentImpl", "classv8__inspector_1_1_v8_heap_profiler_agent_impl.html", "classv8__inspector_1_1_v8_heap_profiler_agent_impl" ],
      [ "V8InjectedScriptHost", "classv8__inspector_1_1_v8_injected_script_host.html", "classv8__inspector_1_1_v8_injected_script_host" ],
      [ "V8Inspector", "classv8__inspector_1_1_v8_inspector.html", "classv8__inspector_1_1_v8_inspector" ],
      [ "V8InspectorClient", "classv8__inspector_1_1_v8_inspector_client.html", "classv8__inspector_1_1_v8_inspector_client" ],
      [ "V8InspectorImpl", "classv8__inspector_1_1_v8_inspector_impl.html", "classv8__inspector_1_1_v8_inspector_impl" ],
      [ "V8InspectorSession", "classv8__inspector_1_1_v8_inspector_session.html", "classv8__inspector_1_1_v8_inspector_session" ],
      [ "V8InspectorSessionImpl", "classv8__inspector_1_1_v8_inspector_session_impl.html", "classv8__inspector_1_1_v8_inspector_session_impl" ],
      [ "V8ProfilerAgentImpl", "classv8__inspector_1_1_v8_profiler_agent_impl.html", "classv8__inspector_1_1_v8_profiler_agent_impl" ],
      [ "V8Regex", "classv8__inspector_1_1_v8_regex.html", "classv8__inspector_1_1_v8_regex" ],
      [ "V8RuntimeAgentImpl", "classv8__inspector_1_1_v8_runtime_agent_impl.html", "classv8__inspector_1_1_v8_runtime_agent_impl" ],
      [ "V8SchemaAgentImpl", "classv8__inspector_1_1_v8_schema_agent_impl.html", "classv8__inspector_1_1_v8_schema_agent_impl" ],
      [ "V8StackTrace", "classv8__inspector_1_1_v8_stack_trace.html", "classv8__inspector_1_1_v8_stack_trace" ],
      [ "V8StackTraceImpl", "classv8__inspector_1_1_v8_stack_trace_impl.html", "classv8__inspector_1_1_v8_stack_trace_impl" ]
    ] ],
    [ "vTune", null, [
      [ "internal", null, [
        [ "HashForCodeObject", "structv_tune_1_1internal_1_1_hash_for_code_object.html", "structv_tune_1_1internal_1_1_hash_for_code_object" ],
        [ "JITCodeLineInfo", "classv_tune_1_1internal_1_1_j_i_t_code_line_info.html", "classv_tune_1_1internal_1_1_j_i_t_code_line_info" ],
        [ "SameCodeObjects", "structv_tune_1_1internal_1_1_same_code_objects.html", "structv_tune_1_1internal_1_1_same_code_objects" ],
        [ "VTUNEJITInterface", "classv_tune_1_1internal_1_1_v_t_u_n_e_j_i_t_interface.html", "classv_tune_1_1internal_1_1_v_t_u_n_e_j_i_t_interface" ]
      ] ]
    ] ],
    [ "___itt_api_info", "struct______itt__api__info.html", "struct______itt__api__info" ],
    [ "___itt_api_info_20101001", "struct______itt__api__info__20101001.html", "struct______itt__api__info__20101001" ],
    [ "___itt_global", "struct______itt__global.html", "struct______itt__global" ],
    [ "___itt_group_list", "struct______itt__group__list.html", "struct______itt__group__list" ],
    [ "___itt_thread_info", "struct______itt__thread__info.html", "struct______itt__thread__info" ],
    [ "_iJIT_Method_Id", "struct__i_j_i_t___method___id.html", "struct__i_j_i_t___method___id" ],
    [ "_iJIT_Method_Load", "struct__i_j_i_t___method___load.html", "struct__i_j_i_t___method___load" ],
    [ "_iJIT_Method_NIDS", "struct__i_j_i_t___method___n_i_d_s.html", "struct__i_j_i_t___method___n_i_d_s" ],
    [ "_LineNumberInfo", "struct___line_number_info.html", "struct___line_number_info" ],
    [ "SnapshotWriter", "class_snapshot_writer.html", "class_snapshot_writer" ],
    [ "Specialization", "struct_specialization.html", "struct_specialization" ],
    [ "ThreadStack", "struct_thread_stack.html", "struct_thread_stack" ],
    [ "WasmInstanceBuilder", "class_wasm_instance_builder.html", "class_wasm_instance_builder" ]
];